const roomDummyObject = {
  cabins: [
    {
      id: 1,
      name: "Cabaña 1",
      description: "Cabaña muy acogedora para toda la Familia",
      url: "/room/1",
      photos: [
        "/images/rooms/room_1/cabin_1_1.jpg",
        "/images/rooms/room_1/cabin_1_2.jpg",
        "/images/rooms/room_1/cabin_1_3.jpg",
        "/images/rooms/room_1/cabin_1_4.jpg",
        "/images/rooms/room_1/cabin_1_5.jpg",
        "/images/rooms/room_1/cabin_1_6.jpg",
        "/images/rooms/room_1/cabin_1_7.jpg",
        "/images/rooms/room_1/cabin_1_8.jpg",
      ],
    },
    {
      id: 3,
      name: "Cabaña 3",
      description: "Privacidad y Comodidad",
      url: "/room/3",
      photos: [
        "/images/rooms/room_3/cabin_3_1.jpg",
        "/images/rooms/room_3/cabin_3_2.jpg",
        "/images/rooms/room_3/cabin_3_3.jpg",
        "/images/rooms/room_3/cabin_3_4.jpg",
        "/images/rooms/room_3/cabin_3_5.jpg",
      ],
    },
    {
      id: 4,
      name: "Cabaña 4",
      description: "Para compartir y jugar con toda la Familia",
      url: "/room/4",
      photos: [
        "/images/rooms/room_4/cabin_4_1.jpg",
        "/images/rooms/room_4/cabin_4_2.jpg",
        "/images/rooms/room_4/cabin_4_3.jpg",
        "/images/rooms/room_4/cabin_4_4.jpg",
        "/images/rooms/room_4/cabin_4_5.jpg",
        "/images/rooms/room_4/cabin_4_6.jpg",
      ],
    },
    {
      id: 5,
      name: "Cabaña 5",
      description: "Como en tu casa y Mucho Mas",
      url: "/room/5",
      photos: [
        "/images/rooms/room_5/cabin_5_1.jpg",
        "/images/rooms/room_5/cabin_5_2.jpg",
        "/images/rooms/room_5/cabin_5_3.jpg",
        "/images/rooms/room_5/cabin_5_4.jpg",
        "/images/rooms/room_5/cabin_5_5.jpg",
        "/images/rooms/room_5/cabin_5_6.jpg",
        "/images/rooms/room_5/cabin_5_7.jpg",
        "/images/rooms/room_5/cabin_5_8.jpg",
        "/images/rooms/room_5/cabin_5_9.jpg",
      ],
    },
    {
      id: 6,
      name: "Cabaña 6",
      description: "Para compartir con los Mejores Amigos",
      url: "/room/6",
      photos: [
        "/images/rooms/room_6/cabin_6_1.jpg",
        "/images/rooms/room_6/cabin_6_2.jpg",
        "/images/rooms/room_6/cabin_6_3.jpg",
        "/images/rooms/room_6/cabin_6_4.jpg",
        "/images/rooms/room_6/cabin_6_5.jpg",
        "/images/rooms/room_6/cabin_6_6.jpg",
      ],
    },
    {
      id: 7,
      name: "Cabaña 7",
      description: "Para disfrutar con la Familia",
      url: "/room/7",
      photos: [
        "/images/rooms/room_7/cabin_7_1.jpg",
        "/images/rooms/room_7/cabin_7_2.jpg",
        "/images/rooms/room_7/cabin_7_3.jpg",
        "/images/rooms/room_7/cabin_7_4.jpg",
        "/images/rooms/room_7/cabin_7_5.jpg",
        "/images/rooms/room_7/cabin_7_6.jpg",
      ],
    },
    {
      id: 8,
      name: "Cabaña 8",
      description: "Privacidad y Comodidad en familia",
      url: "/room/8",
      photos: [
        "/images/rooms/room_8/cabin_8_1.jpg",
        "/images/rooms/room_8/cabin_8_2.jpg",
        "/images/rooms/room_8/cabin_8_3.jpg",
        "/images/rooms/room_8/cabin_8_4.jpg",
      ],
    },
    {
      id: 9,
      name: "Cabaña 9",
      description: "Privacidad y Comodidad",
      url: "/room/9",
      photos: [
        "/images/rooms/room_9/cabin_9_1.jpg",
        "/images/rooms/room_9/cabin_9_2.jpg",
        "/images/rooms/room_9/cabin_9_3.jpg",
        "/images/rooms/room_9/cabin_9_4.jpg",
        "/images/rooms/room_9/cabin_9_5.jpg",
      ],
    },
    {
      id: 10,
      name: "Cabaña 10",
      description: "Para relajarse en Familia",
      url: "/room/10",
      photos: [
        "/images/rooms/room_10/cabin_10_1.jpg",
        "/images/rooms/room_10/cabin_10_2.jpg",
        "/images/rooms/room_10/cabin_10_3.jpg",
        "/images/rooms/room_10/cabin_10_4.jpg",
        "/images/rooms/room_10/cabin_10_5.jpg",
      ],
    },
    {
      id: 11,
      name: "Cabaña 11",
      description: "Un lugar para descansar y disfrutar",
      url: "/room/11",
      photos: [
        "/images/rooms/room_11/cabin_11_1.jpg",
        "/images/rooms/room_11/cabin_11_2.jpg",
        "/images/rooms/room_11/cabin_11_3.jpg",
        "/images/rooms/room_11/cabin_11_4.jpg",
        "/images/rooms/room_11/cabin_11_5.jpg",
      ],
    },
    {
      id: 12,
      name: "Cabaña 12",
      description: "Ideal para escarse del Stress",
      url: "/room/12",
      photos: [
        "/images/rooms/room_12/cabin_12_1.jpg",
        "/images/rooms/room_12/cabin_12_2.jpg",
        "/images/rooms/room_12/cabin_12_3.jpg",
        "/images/rooms/room_12/cabin_12_4.jpg",
        "/images/rooms/room_12/cabin_12_5.jpg",
      ],
    },
  ],
};
export default roomDummyObject;
